---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---



## 🎓 **Education**


### **Master of Environmental Health Data Science**
**Columbia University**, New York, US | 2025 – 2026

* **Core Coursework:** Data Science, Biostatistical Models, Public Health GIS, Machine Learning for Epidemiology, Advanced Analytical Patterns, etc.


### **Bachelor of Environmental Engineering**
**Zhejiang University**, Hangzhou, China | 2021 – 2025

*	GPA: 3.85/4.00 (86.83/100)

*	Awarded Zhejiang University Outstanding Graduate and multiple Second-Class Scholarships.

*	Published one SCI Q1 paper in Bioresource Technology and secured one invention patent.

## 💼 **Internship Experience**

###  Industry Research, Intern - Tebon Securities Co., Ltd. 
Shanghai, China | 03/2025-06/2025
                                  
*	Deeply involved in writing two in-depth enterprise reports;
*	Used Wind Financial Terminal and Excel to create over 100 data visualization charts;
*	Built and maintained a dynamic database for the nonferrous metals industry. Wrote reports by analyzing company announcements, financial reports, and industry news to provide decision-making reference for the team. 

###  Intern - Zhejiang Environmental Science and Technology Co., Ltd. 
Hangzhou, China | 08/2024-09/2024
                                  
*	Processed over 10,000 pieces of scrapped motor vehicle data, using Excel for data cleaning; Quantified the emission reductions of various pollutants from eliminated vehicles by combining localized emission factors; Independently authored the Assessment Report on Emission Reduction Benefits of Eliminating Old Motor Vehicles
*	Assisted in building the Jinhua City Industrial Source Pollutant Emission Inventory; Responsible for extracting key information from over 50 key enterprises' Environmental Impact Assessment reports.

###  Data Analysis, Intern - Tonghuashun Network Technology Co., Ltd. 
Hangzhou, China | 07/2023-09/2023
                                  
*	Used Python to clean 100,000 historical trading records of financial products; Handled 5% of missing values and identified over 2,000 trading anomalies;
*	Explored the relationship between trading volume and price fluctuations for specific financial products; Translated analysis results into visualization reports, such as correlation heatmaps using Matplotlib;
*	Produced weekly data insight summaries to evaluate market enthusiasm


###  Operation, Intern - Zhejiang Soudao Network Technology Co., Ltd. 
Hangzhou, China | 12/2022-02/2023
                                  
*	Responsible for monitoring new user growth data; Analyzed and pinpointed a 30% high churn rate in the "registration-first purchase" stage; Wrote a report to drive product process optimization;
*	Used the RFM model to stratify users by value, assisting in the development of targeted operation strategies; Contributed to a 5% increase in the monthly repurchase rate of high-value users; Analyzed core revenue data (user tips, ad clicks, etc.) over four quarters
*	Identified seasonal fluctuations and growth trends of key revenue sources.


